# Generated by Django 4.1.2 on 2022-12-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
    ]
