# Generated by Django 4.1.2 on 2023-01-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_order_orderproduct_delete_cart_order_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='logic.product'),
        ),
    ]
