# Generated by Django 4.1.2 on 2023-01-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0012_alter_order_user_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products', through='logic.OrderProduct', to='logic.product'),
        ),
    ]
