# Generated by Django 4.1.2 on 2023-01-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0015_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
