# Generated by Django 4.1.2 on 2023-01-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0017_contact_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
